# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Vince Woo
title: Flight Software Engineer
email: vince@vincewoo.com
website: vincewoo.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  vincewoo
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: vinceythewoo
linkedin_username: vincewoo
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
 Senior developer with 12+ years experience designing and building highly scalable applications primarily in <mark>JAVA</mark> and <mark>Python</mark>. Experienced in managing software development teams and interfacing with stakeholders to gather requirements and manage the product life-cycle.  

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: NASA Jet Propulsion Laboratory
        link: jpl.nasa.gov
        # link_text: boringcompany.com
        sub_title: Flight Software Engineer IV, Group 348B
        caption: May 2019 - Present
        # quote: 
        description: | # this will include new lines to allow paragraphs
            - As part of the Europa Clipper Flight Software Internal Test (FIT) team I designed, implemented, and maintained a set of integration tests that verified L5 requirements. These tests were written in Python and interfaced with spacecraft simulation environments (both software and hardware).
            - Worked closely with the module developers to design tests for Critical Relay Controllers (CRC), Event Reports (EVR), Communication Behaviors, and Radio configuration manager.
            - Developed and maintained tools for managing the tracking of verification items and their status for use in release reporting. 
            - Team liaison for Known Warning EVR Dispositions. Worked with other V&V teams to help disposition EVRs found in other venues.
      - layout: left
        title: NASA Jet Propulsion Laboratory
        link: jpl.nasa.gov
        # link_text: boringcompany.com
        sub_title: Enterprise Software Application Developer IV, Group 172B
        caption: January 2017 - May 2019
        # quote: 
        description: | # this will include new lines to allow paragraphs
          - Led a team of 3 developers in improving and building upon the Document Risk Resource Tool (DRRT). Designed a scalable text extraction pipeline with SQS and S3, coded in Java and Python. Redesigned and refactored the DRRT web application in Python Flask and Angular. 
          - Built the Strategic Partners Applications (SPA) from the ground up in a team of 4 developers. The application is built on Flask in Python with a Polymer front-end. The dynamic user interface includes custom D3 components to provide user-friendly features for reporting and forecasting.
          - Refactored the Facilities Search front-end Javascript to reduce latency and improve user experience. Investigated and fixed several critical bugs in preparation for production deployment.
      - layout: left
        title: Amazon.com, Inc.
        link: amazon.com
        # link_text: boringcompany.com
        sub_title: Software Development Manager, Search Data Aggregation
        caption: January 2014 - January 2017
        # quote: 
        description: | # this will include new lines to allow paragraphs
          - Managed a team of 7 SDEs developing the platform to pre-compute Amazon's immense retail catalog search index containing billions of items. 
          - Working with principal engineers and partner teams to evolve an elastically scalable system to sustain consistent year-over-year traffic growth.
          - Consulted on projects requiring unique search features such as Amazon Instant Video, PrimeNow, and AmazonFresh.
          - Actively engaged on various recruiting tasks such as resume screening, phone screens and leading on-site interview loops.
      - layout: left
        title: Amazon.com, Inc.
        link: amazon.com
        # link_text: boringcompany.com
        sub_title: Software Development Engineer II, Search Data Aggregation
        caption: May 2010 - January 2014
        # quote: 
        description: | # this will include new lines to allow paragraphs
          - As part of the Search Data Aggregation team I designed and developed highly scalable and efficient applications that process, aggregate and publish hundreds of millions of updates a day to the Amazon search index. 
          - Designed and implemented features in a distributed NoSQL processing framework in JAVA that supported the development of important business deliverables.
          - Managed search feature requests for the team. Responsibilities included requirements gathering, providing support to stakeholders, and scheduling and prioritizing of feature work.
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Waterloo
        caption: September 2002 - June 2007
        sub_title: Bachelors of Computer Science, Honours Computer Science
        # quote: 
        # description: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
